//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StorageManage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // THÊM DÒNG NÀY
    using System.ComponentModel.DataAnnotations.Schema;



    public partial class TaiKhoan
    {
        [Key] // Thêm dòng này để đánh dấu khóa chính
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string MaNV { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
